return {
  "WhoIsSethDaniel/mason-tool-installer.nvim",
  dependencies = { "mason-org/mason.nvim" },
  opts = {
    ensure_installed = {
      "pyright",
      "basedpyright",
      "jdtls",
      "ruff",
      "bash-language-server",
      "prettier",
      "shellcheck",
      "black",
      "docker-compose-language-service",
      "stylua",
      "yaml-language-server",
      "markdownlint-cli2",
      "eslint-lsp",
      "marksman",
      "shfmt",
      "lemminx",
      "markdown-toc",
      "lua-language-server",
      "dockerfile-language-server",
      "hadolint",
      "debugpy",
      "json-lsp",
      "taplo",
      "eslint_d",
    },
  },
}
